version: '3'

services:
  nginx-proxy:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true
    driver: overlay
